name: Dev - localhost
values:
  - key: user_password
    value: ''
    enabled: true
  - key: user_email
    value: ''
    enabled: true
  - key: access_token
    value: ''
    enabled: true
  - key: HOST
    value: 'http://localhost:5000/'
    enabled: true
  - key: user_name
    value: ''
    enabled: true
  - key: user_surname
    value: ''
    enabled: false
