version: '3.8'

services:
  # Dispatcher
  dispatcher:
    build:
      context: ./apps/gateway-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://dispatcher-mongo:27017/dispatcher
      - AUTH_SERVICE_URL=http://auth-service:3000
      - PRODUCT_SERVICE_URL=http://product-service:3000
      - ORDER_SERVICE_URL=http://order-service:3000
      - JWT_SECRET=super-secret-key
    depends_on:
      - dispatcher-mongo
    networks:
      - backend-network
      - frontend-network

  dispatcher-mongo:
    image: mongo:latest
    networks:
      - backend-network

  # Auth Service
  auth-service:
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://auth-mongo:27017/auth
    depends_on:
      - auth-mongo
    networks:
      - backend-network

  auth-mongo:
    image: mongo:latest
    networks:
      - backend-network

  # Product Service
  product-service:
    build:
      context: ./apps/product-service
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://product-mongo:27017/products
    depends_on:
      - product-mongo
    networks:
      - backend-network

  product-mongo:
    image: mongo:latest
    networks:
      - backend-network

  # Order Service
  order-service:
    build:
      context: ./apps/order-service
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://order-mongo:27017/orders
    depends_on:
      - order-mongo
    networks:
      - backend-network

  order-mongo:
    image: mongo:latest
    networks:
      - backend-network

  # Frontend
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    networks:
      - frontend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
