services:
  # Dispatcher (Gateway)
  dispatcher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: gateway-service
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://db-dispatcher:27017/dispatcher
      - AUTH_SERVICE_URL=http://auth-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - LOGS_SERVICE_URL=http://dispatcher:5000/log
      - JWT_SECRET=super-secret-key
      - GATEWAY_SECRET=gateway-secret
    depends_on:
      - db-dispatcher
    networks:
      - backend-network
      - frontend-network

  db-dispatcher:
    image: mongo:latest
    volumes:
      - mongo-dispatcher-data:/data/db
    networks:
      - backend-network

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth-service
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://db-auth:27017/auth
      - JWT_SECRET=super-secret-key
      - GATEWAY_SECRET=gateway-secret
    depends_on:
      - db-auth
    networks:
      - backend-network

  db-auth:
    image: mongo:latest
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - backend-network

  # Product Service
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: product-service
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://db-product:27017/products
      - GATEWAY_SECRET=gateway-secret
    depends_on:
      - db-product
    networks:
      - backend-network

  db-product:
    image: mongo:latest
    volumes:
      - mongo-product-data:/data/db
    networks:
      - backend-network

  # Order Service
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: order-service
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://db-order:27017/orders
      - GATEWAY_SECRET=gateway-secret
    depends_on:
      - db-order
    networks:
      - backend-network

  db-order:
    image: mongo:latest
    volumes:
      - mongo-order-data:/data/db
    networks:
      - backend-network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: frontend
    ports:
      - '3001:3000'
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    networks:
      - frontend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mongo-auth-data:
  mongo-product-data:
  mongo-order-data:
  mongo-dispatcher-data:
